- pipeline.id: my-pipeline1
  path.config: "/usr/share/logstash/pipeline/my-pipeline1.conf"
  # pipeline.workers: 3

- pipeline.id: my-pipeline2
  path.config: "/usr/share/logstash/pipeline/my-pipeline2-log.conf"  